package com.example.budgetmanager.dto.requests;

/**
 * CREATE TRANSACTION REQUEST DTO - DEVELOPER GUIDE
 *
 * HIGH-LEVEL EXPLANATION:
 * This DTO encapsulates the data needed to create a new transaction. 
 * it transfer data from the UI layer to the service layer,
   keeping the UI seperated from the database model.
 *
 * KEY DESIGN DECISIONS:
 * - Immutable (final fields) to prevent accidental modification after creation.
 * - Contains only validated user-supplied data (no ID - that's generated by SQLite).
 *
 * LOW-LEVEL CONCEPTS REFERENCE:
 * - Request DTOs are "dumb" Java objects - no business logic, just data carriers.
 * - The UI sends categoryId (not categoryName) because the dropdown already has the Category object.
 */
public class CreateTransactionRequest {
    private final double amount;
    private final String type;      // "income" or "expense"
    private final String note;
    private final String date;      // ISO-8601 format (e.g., "2025-11-25")
    private final int categoryId;   // Foreign key to categories table
    
    public CreateTransactionRequest(double amount, String type, String note, 
                                   String date, int categoryId) {
        this.amount = amount;
        this.type = type;
        this.note = note;
        this.date = date;
        this.categoryId = categoryId;
    }
    
    // Getters only (immutable)
    public double getAmount() { return amount; }
    public String getType() { return type; }
    public String getNote() { return note; }
    public String getDate() { return date; }
    public int getCategoryId() { return categoryId; }
}